# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "r";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/etc/nixos" =
    { device = "r/nixos";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/home" =
    { device = "r/home";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/root" =
    { device = "r/home/root";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var/lib" =
    { device = "r/varlib";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FB8D-1EBD";
      fsType = "vfat";
      options = [ "nofail" ];
    };

  fileSystems."/boot/1" =
    { device = "/dev/disk/by-uuid/7552-8E03";
      fsType = "vfat";
      options = [ "nofail" ];
    };

  fileSystems."/boot/2" =
    { device = "/dev/disk/by-uuid/6B5A-B04D";
      fsType = "vfat";
      options = [ "nofail" ];
    };

  swapDevices = [
    { device = "/dev/disk/by-uuid/e80642a0-b25e-4f19-ba04-cef25997bef2";
      priority = 0;
    }
    { device = "/dev/disk/by-uuid/d15d2de6-897f-4b26-964c-5f6e3b843be8";
      priority = 0;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s21f0u5.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
