# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "ehci_pci"
    "md_mod"
    # "megaraid_sas"
    "mpt3sas"
    "sd_mod"
    "sr_mod"
    "usb_storage"
    "usbhid"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.swraid.enable = true;
  boot.swraid.mdadmConf = ''
    ARRAY /dev/md/s  metadata=1.2 UUID=a2edf378:c1efcb74:731a6323:d961e11d
  '';

  fileSystems."/" =
    {
      device = "r";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/etc/nixos" =
    {
      device = "r/nixos";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/root" =
    {
      device = "r/root";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/service" =
    {
      device = "r/service";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/var/lib" =
    {
      device = "r/varlib";
      fsType = "zfs";
      options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot/1" =
    {
      device = "/dev/disk/by-uuid/ED86-22BC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/etc/nixos/.secrets" =
    {
      device = "/boot/.secrets";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/s" =
    {
      device = "/dev/md/s";
      fsType = "xfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
