- alias: Bedroom Shades
  id: bedroom_shades
  mode: single
  trace:
    stored_traces: 100
  trigger:
    - platform: sun
      event: sunrise
      id: sun_rise
    - platform: sun
      event: sunset
      id: sun_set
    - platform: time
      at: "10:00:00"
      id: daytime
  action:
    - choose:
        - alias: Crack open at sunrise
          conditions:
            - condition: trigger
              id:
                - sun_rise
          sequence:
            - repeat:
                for_each: "{{ label_entities('Bedroom Shade Auto Target') }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: 20
                    target:
                      entity_id: "{{ repeat.item }}"
        - alias: Open all the way in late morning
          conditions:
            - condition: trigger
              id:
                - daytime
          sequence:
            - repeat:
                for_each: "{{ label_entities('Bedroom Shade Auto Target') }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: 100
                    target:
                      entity_id: "{{ repeat.item }}"
        - alias: Close at sunset
          conditions:
            - condition: trigger
              id:
                - sun_set
          sequence:
            - repeat:
                for_each: "{{ label_entities('Bedroom Shade Auto Target') }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: 0
                    target:
                      entity_id: "{{ repeat.item }}"
