- alias: Shades
  id: shades
  mode: single
  trace:
    stored_traces: 100
  trigger:
    - platform: sun
      event: sunrise
      id: sun_rise
    - platform: sun
      event: sunset
      id: sun_set
    - platform: state
      entity_id:
        - sensor.solar_shade_target
  condition:
    - condition: or
      conditions:
        - condition: trigger
          id:
            - sun_rise
        - condition: trigger
          id:
            - sun_set
        - condition: sun
          before: sunset
          after: sunrise
  action:
    - variables:
        p: "{{ states('sensor.solar_shade_target') | int }}"
        north_shade_ids: "{{ label_entities('North Shade Auto Target') }}"
        east_shade_ids: "{{ label_entities('East Shade Auto Target') }}"
        south_shade_ids: "{{ label_entities('South Shade Auto Target') }}"
        west_shade_ids: "{{ label_entities('West Shade Auto Target') }}"
    - choose:
        - alias: Open at sunrise
          conditions:
            - condition: trigger
              id:
                - sun_rise
          sequence:
            - repeat:
                for_each:
                  - "{{ north_shade_ids }}"
                  - "{{ west_shade_ids }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: 100
                    target:
                      entity_id: "{{ repeat.item }}"
        - alias: Close at sunset
          conditions:
            - condition: trigger
              id:
                - sun_set
          sequence:
            - repeat:
                for_each:
                  - "{{ north_shade_ids }}"
                  - "{{ east_shade_ids }}"
                  - "{{ south_shade_ids }}"
                  - "{{ west_shade_ids }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: 0
                    target:
                      entity_id: "{{ repeat.item }}"
        - alias: Morning program
          conditions:
            - condition: state
              entity_id: sun.sun
              attribute: rising
              state: true
          sequence:
            - repeat:
                for_each:
                  - "{{ east_shade_ids }}"
                  - "{{ south_shade_ids }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: "{{ p }}"
                    target:
                      entity_id: "{{ repeat.item }}"
        - alias: Afternoon program
          conditions:
            - condition: state
              entity_id: sun.sun
              attribute: rising
              state: false
          sequence:
            - repeat:
                for_each:
                  - "{{ south_shade_ids }}"
                  - "{{ west_shade_ids }}"
                sequence:
                  - service: input_number.set_value
                    data:
                      value: "{{ p }}"
                    target:
                      entity_id: "{{ repeat.item }}"
