- alias: Shades
  id: shades
  mode: single
  trace:
    stored_traces: 100
  trigger:
    - platform: sun
      event: sunrise
      id: sun_rise
    - platform: sun
      event: sunset
      id: sun_set
    - platform: state
      entity_id:
        - sensor.solar_shade_target
  condition:
    - condition: or
      conditions:
        - condition: trigger
          id:
            - sun_rise
        - condition: trigger
          id:
            - sun_set
        - condition: sun
          before: sunset
          after: sunrise
  action:
    - variables:
        p: "{{ states('sensor.solar_shade_target') | int }}"
        north_shade_ids: "{{ label_entities('North Shade Auto Target') }}"
        east_shade_ids: "{{ label_entities('East Shade Auto Target') }}"
        south_shade_ids: "{{ label_entities('South Shade Auto Target') }}"
        west_shade_ids: "{{ label_entities('West Shade Auto Target') }}"
    - if:
        - condition: trigger
          id:
            - sun_set
      then:
        - repeat:
            for_each:
              - "{{ north_shade_ids }}"
              - "{{ east_shade_ids }}"
              - "{{ south_shade_ids }}"
              - "{{ west_shade_ids }}"
            sequence:
              - service: input_number.set_value
                data:
                  value: 0
                target:
                  entity_id: "{{ repeat.item }}"
      else:
        - repeat:
            for_each:
              - "{{ north_shade_ids }}"
            sequence:
              - service: input_number.set_value
                data:
                  value: >-
                    {{ p if ((state_attr('sun.sun', 'azimuth') <= 90) or
                    (state_attr('sun.sun', 'azimuth') >= 270)) else 100 }}
                target:
                  entity_id: "{{ repeat.item }}"
        - repeat:
            for_each:
              - "{{ east_shade_ids }}"
            sequence:
              - service: input_number.set_value
                data:
                  value: "{{ p if (state_attr('sun.sun', 'azimuth') <= 180) else 100 }}"
                target:
                  entity_id: "{{ repeat.item }}"
        - repeat:
            for_each:
              - "{{ south_shade_ids }}"
            sequence:
              - service: input_number.set_value
                data:
                  value: >-
                    {{ p if ((state_attr('sun.sun', 'azimuth') >= 90) and
                    (state_attr('sun.sun', 'azimuth') <= 270)) else 100 }}
                target:
                  entity_id: "{{ repeat.item }}"
        - repeat:
            for_each:
              - "{{ west_shade_ids }}"
            sequence:
              - service: input_number.set_value
                data:
                  value: "{{ p if (state_attr('sun.sun', 'azimuth') >= 180) else 100 }}"
                target:
                  entity_id: "{{ repeat.item }}"
