- alias: Theater Blu-Ray State Update
  id: theater_bluray_state_update
  mode: queued
  trigger:
    - platform: state
      entity_id:
        - media_player.panasonic_blu_ray
      to: null
  condition:
    - condition: not
      conditions:
        - condition: state
          entity_id: input_select.theater_bluray_target_state
          state: "off"
  action:
    - service: input_select.select_option
      target:
        entity_id: input_select.theater_bluray_target_state
      data:
        option: >
          {% if is_state('media_player.panasonic_blu_ray', 'playing') -%}
            playing
          {%- else -%}
            idle
          {%- endif %}
