# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "uas" "usbcore" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # cryptsetup luksFormat /dev/sdb --key-file /etc/nixos/.secrets/vkey
  # cryptsetup open /dev/sdb d --key-file /etc/nixos/.secrets/vkey
  # mkfs.xfs /dev/mapper/d
  # mount /dev/mapper/d /d
  # nixos-generate-config
  # copy/paste

  boot.initrd.luks.devices."d" = {
    device = "/dev/disk/by-uuid/b82f9947-51b4-4a41-af96-32baee7e5e35";
    keyFile = "/etc/nixos/.secrets/vkey";
  };

  fileSystems."/" =
    { device = "r";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/etc/nixos" =
    { device = "r/nixos";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/root" =
    { device = "r/root";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/var/lib" =
    { device = "r/varlib";
      fsType = "zfs"; options = [ "zfsutil" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E141-62B8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/d" =
    { device = "/dev/disk/by-uuid/eeda77c9-1a75-4c16-9a3c-a1fc6fbe067b";
      fsType = "xfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
