#ENC[AES256_GCM,data:DVpnN+bPvs2M3F4=,iv:aIJbqzyc4LBwxe/nO8UUnbMEdsOIsv+U6W2xQ6Tn9rQ=,tag:skEX26zrcUWKNFMZpriegQ==,type:comment]
#ENC[AES256_GCM,data:w8E24vRb3hoB0nGjAqIX2Or81OxByNNsMHuMvOBhY57kcvp020YARrnky0Wnugl/tIOUlZZUlF4Ock+PAXs9+h8HCPRgSKZl/MS7NPR6JQ==,iv:Hl2G9yav7apLuH0wfesMRPfc7wiaKfH4NhW+9Ni5bSA=,tag:mK+ggr5KZ9qAyQaQJzknlQ==,type:comment]
camera: ENC[AES256_GCM,data:5L3jgJROO9jwC50vW8n2+qNUtFE=,iv:pukS6NNoOBSUCQJFjLaG8/UQcHEBxjFb34sRfolJukU=,tag:qkbDDlodG58fZaBBsoGS5Q==,type:str]
doorbell: ENC[AES256_GCM,data:bIh3aY6k05Zp9lpnVMJgP/Wag7M=,iv:QKfvL09YE9cL1Bg2OblAp1pdVohIwaqLn6SVxiTOM28=,tag:MX3G0MoUpdhA0ihk6xsy+Q==,type:str]
esphome: ENC[AES256_GCM,data:IeLumygcQddpOyFvFq/ymcKoxOs=,iv:EsPfmfW5wwtnAjV+KSPZxCMNJsF6AAk7nl8OvXHOA+I=,tag:0kFLKge4fR8vG6aqY5rQyw==,type:str]
esphome_hashed: ENC[AES256_GCM,data:1NTMJ/j081pO+G3Dmv6LZB+iG5ggmhXG+suZYO4AD3jolN5stv0ksBV6B8eu88HewwlwsgcptshZVvSf,iv:WnqoR7kDT5T8Q25PdVN94aErVqQ/QBamJXlL6IFPU4I=,tag:BNEv+KA04STieIchF2R7jw==,type:str]
frigate_plus: ENC[AES256_GCM,data:3fMfJxD+X9U1GQMhTpwItDE0J4kqXUNThx8V9iZMyAMIMOlSarGfY3Fbp97Dj6sIhYJxQTnx0gHnUnQcckKOCZSkeCRkUyaOXc5zKqU=,iv:X+KWmhZAJ3EBlx+gVaMgLaSvNqAHSSlViVStdcdQ7UY=,tag:rR8gsnahufVqktIgJX+7YA==,type:str]
journal:
    AUTH_KEY: ENC[AES256_GCM,data:dO8bUmnktxXMbjUoZUg6H6xJMgOEakLC5PMFV37IN8t8Mgpq0R9K28fYO+oY25pLKCiiM2lXT9/P5fpbsWqm1qZo,iv:YAGZTlEGCc2WwnBlU6lqNh4Uu92kpMhRDNKp2I0Cl5o=,tag:u72HeFPdi+zKlYqXVYh2Zg==,type:str]
    AUTH_SALT: ENC[AES256_GCM,data:AqZ2lYFb0T/CvBepcq2x6DPpoa8IgTKkKtPxQHtTbgC21x4QTdUrsfFn5DB5DVd4Dx5CoTlAWHySnHrNLDJR2l2i,iv:3DVl/K4LRxZziL5HLC1NV8P7rzWPtTZfqU7FQZ5Qs+E=,tag:MsSjaqwCItHBcWXXpulbYg==,type:str]
    LOGGED_IN_KEY: ENC[AES256_GCM,data:YZffboTB/OqIy+4C/6GYUml3aGaYBfXqDa1vDXu+HWqIdGUOIWgxujReXnMikXMrLPlYuzNHohjxzrAqURA9VufC,iv:ZW8lf9YlMnjfIS79PdPQ0o9o2V8NZOdt+IDrR35BcpE=,tag:dEAb/c74se9bEPtcuHipYg==,type:str]
    LOGGED_IN_SALT: ENC[AES256_GCM,data:RnUr5p2BmSuI8Yw1jFF2Km5t7PxG7ibKgZKclFwQ0M5mO7GQyv77gc8xAbiyGK4Loo21PT11fof6Xhq8YaEyUvBV,iv:rctNTYDb1QqIAmCgoliEi+vKoK9TUqwzuUnsdVavd4A=,tag:XYLw7oBvex75JErclLYaow==,type:str]
    NONCE_KEY: ENC[AES256_GCM,data:RHFytkBjFCAXLrcWGyGXiKbtURvzhy3DFXfzraKIc8WoWlDPT4Gfx5N6KTzVrErErUYB8F+j4/i79ZWmR0QJ1p4W,iv:345T1qv2bLWahuAsYudlNn2l6Zv0LlpUmD3XWfSnIh8=,tag:PYPg30mKaF8qFwy3PUePZA==,type:str]
    NONCE_SALT: ENC[AES256_GCM,data:/Y6vb4DSO47ymoVy09Wtgw6dXjXYcICCSG1Beit8VX7xjzWO3Sy9kQJFrUz7t8PXl/5GLBcirTBUbj+XjSZmE1/e,iv:7QspUnwH0ektRynuA+nzuEBafwiB0b4Rbh7i1eD07Aw=,tag:VHErWgBvQLjTcTqewXvUGQ==,type:str]
    SECURE_AUTH_KEY: ENC[AES256_GCM,data:K/a2IHQkO+DMNAx+73CLGaubYMPoRTJkJN+5NV/UOBUih5xvwe7F690leowQ7hPROdTaUBVHv1BIt+qv6UJADbMN,iv:htKVoq0Mi7o4/q9yGimPIHJrp/2gSgggQ4V3Z3AhZIs=,tag:na1QrtlT3yIiRIKH1D1S2Q==,type:str]
    SECURE_AUTH_SALT: ENC[AES256_GCM,data:dhK4DUwFn9rS6FB6VBaKp4i87ZtK+jBcfePIFdw3HpPeL1rmNv4t16tQoqdvG9D4aY3gMy3uZYlRtErVEhy1TFZl,iv:XsRWUsCRua3ZME6uDvRRrng57LboqM1tFDWcegZW3+Y=,tag:kb9F68kV5J7EOYwMJMQ90g==,type:str]
    dbPassword: ENC[AES256_GCM,data:uDujxIbrx3s8n+Eg4Tb/KPyFU7c=,iv:J4EslxSUNPifox9ZKh3Ej7qvUakZP43ujMTCXHqJyzg=,tag:QFB5NvHkRDvgVtohfgH9aA==,type:str]
joyfulsong:
    AUTH_KEY: ENC[AES256_GCM,data:xdDKwviPylzUUj6yTtt7+bkmt4NMMOOS6cSy+pWXge+9l2pl7Xm/BqCQHcdZhTbb1iIDr5oCSD7j4TJkFamnXw==,iv:IaEiBxhq14slGmT7sHShvQNpTu2g6lLkLVv0tMp+u3s=,tag:u6vlOssLBBiyW8Ys0lMn/w==,type:str]
    AUTH_SALT: ENC[AES256_GCM,data:Ixsi64gRfilhDEBeCfBgVqiVgJ/FgOyRzIS2+Kzx711sbxmqqLDq7g9gUsgdy6mp7NioDJ4yR9xZYXK8/WYUEA==,iv:rfoAXrQmKE5l1m7waHVYhobF5MFETSZ/yO+8cjDQtY8=,tag:A3rj1ZnWMgB92fWNWear+A==,type:str]
    LOGGED_IN_KEY: ENC[AES256_GCM,data:qB37FhSqZGddi44RjbDAJOTJFO/YJZ4TMO/XsDeWknc35iGAeRu4IyKtiYPIe3PLma2D3bKYq9fF1xTqBa5orw==,iv:0jAscxOwmW9XN/rwSjJynNAvDc+pdFzT3b5XP4wMRTg=,tag:YP2h6gS1SQKD0aIi655UtQ==,type:str]
    LOGGED_IN_SALT: ENC[AES256_GCM,data:Git+IS5f5SnITCIU9fX/qqMDG1g01FnoUT32DBlweOhSpeIaPUqWim0hmZpg1S6uhoARopXn9Z3jRcP7By3xYQ==,iv:sEzjV0h4yoxqpBKh9sG2ZNYSy+KDlUeGYnXHw/rFnYs=,tag:dbl5jifqX7T86hmmp38Atw==,type:str]
    NONCE_KEY: ENC[AES256_GCM,data:LPVAqqwv8HFKWTo0nN2wULPxgpGonJ5lO564igJR7Of2c6UNs550SceQefepPWQjbXSnLUA1sLoNDE0cTVaYQQ==,iv:2pM7ydhY34dgeBxvLXs2iXCdupK7NJTmvGrmgzPRNkg=,tag:FYbnGBWJVk726ri7G+yvQg==,type:str]
    NONCE_SALT: ENC[AES256_GCM,data:XxKHDyrBf0zYS7pNt2fwHWRNLhG98l+xfP/d9Mt3CIsHBK8KwomTRN1onMStBTIst6X4nknjtGMB7Nv8j1WNdA==,iv:vhTZiJ3lHv+9tJUwVDrmyJBelHs0S2mGDxiDzGRkyFg=,tag:Z9Su35PUiAkROfjf6nwFCQ==,type:str]
    SECURE_AUTH_KEY: ENC[AES256_GCM,data:uZx937zTbW4CsOdd56GO65ilO0+KKet8R52F9iztpi8byAcYyG9taAQjS+q7p89l/flEiajgdyxcPflGev3OKg==,iv:6wRhQFQgnKjTMdlvVUeX6mirNpYSglNNw3YwfagFGUo=,tag:E1g3jHtZrS4ZIiDl0Duk1g==,type:str]
    SECURE_AUTH_SALT: ENC[AES256_GCM,data:PkkETX2bzcKpOT+MuGRsJurISolhwMbKY0ORz89NaEtPhNEsmf1KafxXaykdEf1/Wc6b2X1RbXXTFO4ku8gwjA==,iv:G52qjaA9pXON37AiGjESStxuMsHHKS/l0skfavGmXZY=,tag:IbISjnyrZYX2ld1njj0ImQ==,type:str]
    dbPassword: ENC[AES256_GCM,data:vTXY7NA3utDd2lj92K4eJJ2apao=,iv:AxHW7YEhXgpBP711OpaWIlusKL97QRJzEz45DLPzpiM=,tag:dPDciav5XTLPacpukUaaAw==,type:str]
mqtt:
    frigate: ENC[AES256_GCM,data:eHd0QV771496FO2IiCpRfFGxPP0=,iv:QGW0kTXP0XePiQ3/g16eKfaQC9KtaNg1yufvZcxumpE=,tag:G9EGrr5B4TMln+gc4cWDlg==,type:str]
    frodo: ENC[AES256_GCM,data:8NbFka4NP02WBeMLnteaydDdm+w=,iv:bX5v0VjHFo22MFKUQOASrt5YRJ9v/DvmSnWP+Rzk5Mg=,tag:QlqU/ut7oi59XJpRSx+Riw==,type:str]
    ha: ENC[AES256_GCM,data:Ssa4/2SDfwuyF+gaAA5iPOL4rmM=,iv:x93BQeHmjznJ88+liXaqeKL0CurJZkKlyurgXjOkT70=,tag:6LQ90UzGM4DClK8+23qFjw==,type:str]
    merry: ENC[AES256_GCM,data:YScFeGhpYcXnM80uUgHJbi0aDxE=,iv:CyS3s8/UB7BciYhnH5QHhIYBvnoTMJghDGR2VvYDCWA=,tag:RkaPcqC1q6dSX6RgYV5iGw==,type:str]
    pippin: ENC[AES256_GCM,data:XzhLecQ7skBHIvGcaDcioNATjmo=,iv:UqA7hPrt1W4V7NAeoGUg6OMy2/aW5ln3fLZ52WRPcAc=,tag:EU3NyZxYxEaJZ9ce7WW1oA==,type:str]
    sam: ENC[AES256_GCM,data:uCALi79MWCnDiOvrSXbOlbPF7lk=,iv:dtNTJuQm/IfNd2NxZzr8RRkBnUK3gDh+RN3G48Wn0mo=,tag:Zf6cEIuYsil2SD06cya9MQ==,type:str]
    server: ENC[AES256_GCM,data:hSGvcy5ZkJGd+9CsQ70F/mIgZKg=,iv:NPq+6sn5EL1GjvuShuM6MDONs+VhMVhUIXfyReN9f1Q=,tag:9LGqXh06KTakb7NFVM/ITw==,type:str]
    theater_remote: ENC[AES256_GCM,data:Iib6vudh/DHkWNgIvC6dNvHWZHc=,iv:ReFxuG6Brlr7qOvSElUprKI5Pms+xMiWaHwuCEKWqCE=,tag:3wc34+Y0faEwnRSc4esbJw==,type:str]
    zigbee2mqtt: ENC[AES256_GCM,data:7EHKzdMbzWHNJW9xgWeSg3RZjtY=,iv:niXPpHnhd1O4kP3vxefJW/YLHrCLQ4kAD5kyRBAwZ98=,tag:D+0yA7MC+7ZA+1VRWECvqQ==,type:str]
nanoGpt:
    apiKey: ENC[AES256_GCM,data:titqOxia/8dtFZJ6zf3cSFNZB2M4sqC2qm+HdfRKJTpMEzSPwh0Lyk/DNlk=,iv:6Iv8oK+QZSY6wO1Kn0gTzwIYKqs3MPu6gYU3BpN8SLY=,tag:zI5XZFqY56B+L3Wfs/0rGA==,type:str]
onlyoffice: ENC[AES256_GCM,data:9yQVcMSruExeB3tft+Fg+VOunJI=,iv:fGWBYAKY/pjjvo3ggad0BdGulRnFlSsUvrI8X2rKw0A=,tag:8ggT5fsp6YO1mkjC0eKPAQ==,type:str]
openWebui:
    secretKey: ENC[AES256_GCM,data:G9XjltOyPNra96fYNJfdd/KIy/k=,iv:C8xgJjecNv1J2iGrOvp4oFC0Mh0TTHjj8ExpMXPgQdM=,tag:qKWOYTNyBJvB72TERIBgAg==,type:str]
owncloud:
    admin: ENC[AES256_GCM,data:FjFo8poJe+Ggup/iXFEQWrK9V3Q=,iv:UL6+gRD0tQGFdgbIyySsIWPp1QCyd6QH/njCbpyPvhI=,tag:S+nvEvHjH+Xp149Qh3iYjA==,type:str]
    db: ENC[AES256_GCM,data:9xt9JsfOMCemd+dLiDVwk0k6KMs=,iv:NGcchNbDBFKF+DTVwAsJdz2Ox/QjQCamIgEAXlXSB34=,tag:V0lJ8LirPalwYY7P9AWQxg==,type:str]
pihole: ENC[AES256_GCM,data:GeGAnRHjB6fbNt2uzm2tNeWw9sQ=,iv:8fuOrYAOGt+uxDcz3y/7Q3at1pS4nWiyiJeTF3hEuXM=,tag:UFC2Yq8KWVGBf7N6yciAnQ==,type:str]
samba:
    gustafson: ENC[AES256_GCM,data:DykrkXeo,iv:gzSezVoRGY2yKFiGY13VCu6LF8SF7kxGGke+CNYatKA=,tag:lOazWrVRfOdk6XJDJNvcMg==,type:str]
    josh: ENC[AES256_GCM,data:dt164AUwKug=,iv:G5/susIotBotcQcPnGM3ub6T//H0Cjt898xkklCXkxI=,tag:D0T4pSXRDNiVWxnoJMUcxg==,type:str]
searxng: ENC[AES256_GCM,data:emJyQ/tbwrYPO6tSgVy2lDxKvS8=,iv:ZvsY856kuoIhzPRifeqo08Ozrpb5BIUiy+u2PWuG+Xw=,tag:dV9zr1pdWZB6OIhFKNla+A==,type:str]
smtp2go: ENC[AES256_GCM,data:yTn6SaddjD66/RSrfTAESw==,iv:Givpq1AJ0eSAJ7tJTlzEjdsivn5j5bsai5rJMInQ2Zg=,tag:mljcJ9velAZW9P2uJ1/03Q==,type:str]
transmission: ENC[AES256_GCM,data:YPmkeWVDjKy7s9gcnqqbLrib8Gs=,iv:78TXzDe312A4wo1YvXRk2VXUl7uOXWFTrs73sl9lo6I=,tag:u6TBOtw7nsAWO6tpqlUeTQ==,type:str]
ups: ENC[AES256_GCM,data:VB4nAHiMTO0t9gW+3kEphGnOLwo=,iv:PLv8fEPMJ6ffBQaSLkp7vcPquv0H+Eskr7YA5G9TsCg=,tag:D3MpeAwyz+fda+EOd2BwuQ==,type:str]
zwave: ENC[AES256_GCM,data:3bkIzaoF52gJ2+8g7YHMELJfQT4=,iv:ba6UJ0wJbLeQctfkoUvqk/zi5rNexTCGohyxam3+Ip8=,tag:IJXO7u8HVcztKa6UwdFD8w==,type:str]
zwave_hashed: ENC[AES256_GCM,data:RTIX6xP/URFRs70x/68VhhRpMQr1gbamxsgY82spHNsbJTbcTguKIQ5NTTsTrTf58maYRD4AgcxGpxPJ,iv:lYz9UY0GY35T8bYnsEPHAUyrWgrh23RMAlwKK2iqdKs=,tag:b2+qNc66aFRvsOlmDA2+2A==,type:str]
sops:
    age:
        - recipient: age1jxuf7pg7vpcye928qgx3uxzvgcrrpac5pn4844yphctpvuef530qqs59wh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibFRwVzFDY0hkaE9JbmZ6
            Si9vWHY5SVB6aVI4VVgxU0REUW0venZrSkI4ClUyMVN1dHkyMmhlclZnQ3FpQ2Jy
            M3prV1puVGN3dmZINzFTa0hiRVZuQ3cKLS0tIEo5Yi8wZlBxTlA0Zml2aW1lczVi
            TXNJY2NUZ21HQkVqN01CODlCdTR1RzAKV1aimjm66eojEtwZAAWYORgM73b7DOmX
            azqvSCP+brEjBYQXzCvIM6SrEVjp0b+1oa4/SjG0gwCogeXaBoDiDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd3pdegptd0jz3pktjjv3c4z9e6l6jpywlrgp8kftnrp8arjvp0qujyk2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dTVvbU9RNlp1WWVGUXl1
            bENLTWJ0Nm1zRXMxeFN6RmI2aFBkbUJUWlVvCkZONHNNcFdnUE5MTzJFa2NEaU1R
            akJ5c1JuTHgwWEVWQ21Pakx6ZHpEb3cKLS0tIDk4K29lQXhZN2lVZWxJeE82Uk1Y
            dVJmL2piYlIwelIyeUxBTGZnSGdqMk0K1bdS/0s8TYdL6vGz2Z1lf3YJ7E+bnSK0
            69lNHPz/xX5UhjzH7lFZB3TMeIpWf9rlkYBge1QPsA/nctByejY0CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t2mg5qfgnh9jt0h824yprvux7hl837sxhqn8lgacxa4msm53hspqpx8q9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUitvZ3JoTG9nRVFvM3ln
            dHRMdllmNkNnbFJRbzhlaWh4VDBLRmg5N0VjCjRPbXRzNmhGV01ySE1ZcHgzVVgv
            V1QwOTN4SFBIeUgyU2ZZZkRxT0oyTjQKLS0tIC9YZytDRTIwU1htcTdHSGdkOFd1
            S1BSN2RoOWNyTWhRK1c4UUd4TXlWUDAKd4EFIfXebztUjOh6HCsTYYatgX7ok5ay
            Mg1TfWXwLm0PxaPIXDABNT4QAtAKxCgk3bN8D2gjIoK4ngP0GO6LJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1txypm409yzc6hwyepjgnj288ph4c43mdme9c354a45msc69hjpts0p3903
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHBrOUlHcVJXc1U4OWcy
            N2pzdDRscFFiMHEra3JGUXlRMTJtdkw4a3dFCnl4OGxrZS9YSnE4MFE3TzRiU3BT
            ZjJxbHd6WW50NDZncFVFYWloUEViaU0KLS0tIHpxRFYvVkQ0Yi9CTWZaWDgwM0FI
            alRzTVY5SnEyc2cycytaN0t4d3kxajgKvKiWV42SC4vh1hwzPaAFN8BovI9cI3Dy
            lvRKJ8lcLGStHhAABtEwgituPcgJFoqQaWl3za8nWzuvIvhNdDEGdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14mtzynemax29ls25wk7s72lfnsmqwsxd3suj7a24zxprkkxufqtqfmkq4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSUN6djhRWnh4dDVqdS9x
            QjBlOEVUZk9Qb3V3SWhzeEhwS0VFZ1dDYW1NCjRyWERKQ2hQVzBLZGF3UTRaT2VP
            NkFreUs3Tk9za1NQdHI5OUdoOEFRYjAKLS0tIGhpeWtVN3JqSkliSC9JT1dtZ3FC
            M2d4M1lXVEhZQXlNYzhGVGR5dW0wU1UK+00X0k4AhwF9Z8XF9cvqNwgNTgAC+zMA
            fyx7zbgoVNUo95s+CrkLS94AQ6eVIdYvff/bJw0WUH1EZlFv1Fr0qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u8f5qmensfddyqcrhzy59uyc5qas400lkvmystkvasxgm3clw9kqs2aya0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWhqa1VXd1Rnb2VqU0Yv
            MGtjc3FXMXRKL2FER3pZS1FWcUdxR3NRN1g4Ck5VUEZzemNvTWRjVnY2YkkyVGN0
            djZCb3ZBVHUzc1VGcnVoQmNhbEEySEUKLS0tIFpkdkNNTHZZK3lmREYza2FYZTZ1
            Zkg0bXdCcHg4OCtSN2pQa2txR0lPcm8KQXUtPNCAnc2o+oaP7Opvlpf75UaVStNa
            mcZH0CH61mCdrYui6qyr6EOpf7yQTMlEDkyejuNBmr0bdsSou6ZWbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T03:03:23Z"
    mac: ENC[AES256_GCM,data:gegN6Vkz2jMNY8UCSb5u1UcDCDNk70ey0hpTIKjeZ3tHvIty6Wp5CCkIt92m+xc8hRXpCwAan6bEMYMDkWSEaqrQv2yDjAx0Rxm24u0vgIHgG82yoKWglf6uCOlz6seIBvGGjssLlMytCbb07f36dKLYdEfdOiwLMdM0/vrxp3w=,iv:YQNIx9hwlyNwINGYJM3sPEGpD3rcPy3w/s26zBn4pq8=,tag:zvd3WqL4DaMX90i0TS0jTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
