#ENC[AES256_GCM,data:1Z3WyYNfOtSuBLGL1hbsVh+FuIzT/OgZ8pDBwO72JbTYYEWN+Sn6b+cVDqK/KCa2ZGs=,iv:fKTx8xJqLfVbpXSbT3jzA7xREKNC78mkMBbmYM6HjY8=,tag:KMl7FxQik4904caRpsF/wA==,type:comment]
#ENC[AES256_GCM,data:DVpnN+bPvs2M3F4=,iv:aIJbqzyc4LBwxe/nO8UUnbMEdsOIsv+U6W2xQ6Tn9rQ=,tag:skEX26zrcUWKNFMZpriegQ==,type:comment]
#ENC[AES256_GCM,data:zWuL4UUBeLt/2U/y1ikJ8CQawSBDniaffv7Tz4uoFbo3hexM3H+UTPt+9JSeWMlWjw8ij1ZL6WiWisv8774eFvBzNLTyTnP1kA1zUHU=,iv:xFotkyO45mRcUcWBotaRkMPwdoaVCpXYp89fPDJjbFs=,tag:aQHOGcH8tmhnYK4PP5IKnQ==,type:comment]
camera: ENC[AES256_GCM,data:5L3jgJROO9jwC50vW8n2+qNUtFE=,iv:pukS6NNoOBSUCQJFjLaG8/UQcHEBxjFb34sRfolJukU=,tag:qkbDDlodG58fZaBBsoGS5Q==,type:str]
doorbell: ENC[AES256_GCM,data:bIh3aY6k05Zp9lpnVMJgP/Wag7M=,iv:QKfvL09YE9cL1Bg2OblAp1pdVohIwaqLn6SVxiTOM28=,tag:MX3G0MoUpdhA0ihk6xsy+Q==,type:str]
esphome: ENC[AES256_GCM,data:IeLumygcQddpOyFvFq/ymcKoxOs=,iv:EsPfmfW5wwtnAjV+KSPZxCMNJsF6AAk7nl8OvXHOA+I=,tag:0kFLKge4fR8vG6aqY5rQyw==,type:str]
esphome_hashed: ENC[AES256_GCM,data:1NTMJ/j081pO+G3Dmv6LZB+iG5ggmhXG+suZYO4AD3jolN5stv0ksBV6B8eu88HewwlwsgcptshZVvSf,iv:WnqoR7kDT5T8Q25PdVN94aErVqQ/QBamJXlL6IFPU4I=,tag:BNEv+KA04STieIchF2R7jw==,type:str]
frigate_plus: ENC[AES256_GCM,data:3fMfJxD+X9U1GQMhTpwItDE0J4kqXUNThx8V9iZMyAMIMOlSarGfY3Fbp97Dj6sIhYJxQTnx0gHnUnQcckKOCZSkeCRkUyaOXc5zKqU=,iv:X+KWmhZAJ3EBlx+gVaMgLaSvNqAHSSlViVStdcdQ7UY=,tag:rR8gsnahufVqktIgJX+7YA==,type:str]
journal:
    env: ENC[AES256_GCM,data:r3DNqGDPUfHX98PYAn+oO1O3GwMxh+aGF5TRHiDosiHAA72CzBEUQmEIZ6/KpB/NP+3Hw32XU+41LiLTTnGBYGvoMkOu5Aoom9hvkdylW3MYoFxgwFcA7/JVRxmFM5K4hdVmD48qKH2R7rzDyYo8+9ysZ7m80UsvnIQO1+Vwf0M0O99Nn+BCvCmT//h6lao0dDpJeKMHKYzERr8jWip/MI1z8ZcRSU6P5/MzhfHcZjPamO/+3JzVUFv/C8b+B2ReyqCnJwWwJwxEWPaloDPUfZWoDJYyyVWvYL/iZHBAmO1VGoYS0KKUi2pfMnvzQOtDUf+QVNqGwRvNmeVlhURYdoUqGHcn2jXVkXFzT/mZaIt6+CPk2xDqRDaMOeUWunzdORmIaWSVyW1fZ4DEu9qBjJlSezC5vocj5If2G/0Hz/Z64CQ0KTqnPa8Zgka0biZRRN5Y0OknIJR4956IiiL8u5tDsmzFFtEG1RowUkziyo78Nq7uyAacbxvATsCYFolR9yvSLrx2L9o5Lrd2QFVu3ig0MgyrM4+RY0LVvZ7t0hbaQ99PVU+UGZZxQ2GTiT6HDYrrYbDiip1O12TYw4L1kWBW3kDkBs9+pDpd6f89RhuSuXm+PejjWjnjd54qAXeT6mhC4O0sMQPnnSP0wHLNHVyKRqWtGAoh+YlO3Y2dyw2GUTzUtwWQB7lnsZRrvEbduKf+vHyn7ueDbceAM6tKeELCG1IB+gr3ywOCf4wP7NQIWSY2BxpOynmwJ+4g181/3SvAolEwUadxvez8JTpUlgpTqsPy5g0NEl1qRjPBPfx/kYSBwlgf5oAMs1FcbirpTyaFnTl6E5sHMbkHQo7DuYCdPE9YdzGKNTU8/2B3e8AUm1jpC7d7esN4tOH1T/ZT2YXKmusmxKmc16YW2I0HMa513tSXxiX4Wv1fSuq4jzHNLcbVc4xVORhLa2wnOtLGRmwwpItj9V/mZIVugQZCRshee+6oQUQAkqJiQhfx7q2wIdLZc7jlOXI=,iv:fgrK1Kuno0251EX0z8lnKQxeuyGfkQL/eI3n/IybUVE=,tag:NgVlP2YAmWHHaDP8pTGL7Q==,type:str]
joyfulsong:
    env: ENC[AES256_GCM,data:uCJor8gezq/NnHVjhLUbT9gcv2QaCr/fJIYLfkdvFp6XFTKtdoqGGRsgDM8r8jGFYQI6og7rJtoAmyGaZEBdlKzFig1xMeRvCHOCbyWcnpFYvvZ6uk0TvQVtwlIPUZN2rOwQLB9aQ+vvD5iL0wU23MleUs/nyLbEBgVHPPMLUV3y/YQM1TTHiDLyIA0WqC4dkZIWK0JTJ1RNQwxPV4+SJCSHR2GgK0GAFyYY72KMRrP7nuAw+Z71GCDZgAnWEnOvNqyiy/Sh2WAFLT7azXO6KkzuaJtrdBEaIwTweN5+Pfgafnq4bjtNb1SARk9MwuhUvSVDxIzRDpv3JVwYoigrCHMvYQG/T4J08JMQTNLsXgo9BoQaspWdU5SAeLsISJVeBRgn7SC60gHO3JpoFymYIvsVL9k0/7VrrXlsuCvj1jqgD2aA4iPtg/hnNo3iYZLcQyROPLbgSg8wM1VF2BE5D4PLxC9gAy+beQBtuil/Oy1NTvZAnDj5Mfks5xRbiLHv53oeWrylSzSQ364zHcJB3PEZHGEbgHOnfPPoOEhRmJrSyCoCJN5Agkjs1T8CJk+s8gc9gHipD42/K/OUw7+mBi6akzvTe3V0af6AGGGh8t/rPw4C/Uo6BQqfe5PxKb+NuTovHTXBT1Dn5gEa6J11ftD+L7HRH+lNh179U9a1Itjd88nLikjR8d5vySDzga0M8BIsh/lZZwuwL0PIyeaCZEa8f5320kD6wi70wdL7w0yGrV19RBmg5uDMkTkGgwCxIZ3lwdWXAqutRR735+k30guiYXlygzKk4FC/jZT1KViFDgRfxumA5jiJC2Jy5jzmH3/qHwSdq2o4n74VOFwmcif+5TiqycN37i0gsma4/5hug+RI8nbSibGREoPIsbgMW5TA4Aml6LyM0NXXL0hXtaCyRjz4+u68OM525nFYFmrKqPjHFBdO9uiINKJ4xXJn9OqhM52HsFlrlvhl33D0lV4I8WlF+y2Hgg==,iv:e11TXYTXPb7P3F2WwWBPYP7fJHLjAtPCFYN90sKP7Ik=,tag:Jv6yhOVRiYxVwDd7svOu2A==,type:str]
    db-env: ENC[AES256_GCM,data:iRuLUWvh+9l8ZS5WHom7UAZQBYfQKY9yuTbY4DMzRVpEfzy624s=,iv:bFy7mD2DV2QM7jyNtjpLBNFcofhwPiRUsybYFYg4yuA=,tag:yb6KGbFuXxkmzu8Dit5bpQ==,type:str]
mqtt:
    frigate: ENC[AES256_GCM,data:eHd0QV771496FO2IiCpRfFGxPP0=,iv:QGW0kTXP0XePiQ3/g16eKfaQC9KtaNg1yufvZcxumpE=,tag:G9EGrr5B4TMln+gc4cWDlg==,type:str]
    frodo: ENC[AES256_GCM,data:8NbFka4NP02WBeMLnteaydDdm+w=,iv:bX5v0VjHFo22MFKUQOASrt5YRJ9v/DvmSnWP+Rzk5Mg=,tag:QlqU/ut7oi59XJpRSx+Riw==,type:str]
    ha: ENC[AES256_GCM,data:Ssa4/2SDfwuyF+gaAA5iPOL4rmM=,iv:x93BQeHmjznJ88+liXaqeKL0CurJZkKlyurgXjOkT70=,tag:6LQ90UzGM4DClK8+23qFjw==,type:str]
    merry: ENC[AES256_GCM,data:YScFeGhpYcXnM80uUgHJbi0aDxE=,iv:CyS3s8/UB7BciYhnH5QHhIYBvnoTMJghDGR2VvYDCWA=,tag:RkaPcqC1q6dSX6RgYV5iGw==,type:str]
    pippin: ENC[AES256_GCM,data:XzhLecQ7skBHIvGcaDcioNATjmo=,iv:UqA7hPrt1W4V7NAeoGUg6OMy2/aW5ln3fLZ52WRPcAc=,tag:EU3NyZxYxEaJZ9ce7WW1oA==,type:str]
    sam: ENC[AES256_GCM,data:uCALi79MWCnDiOvrSXbOlbPF7lk=,iv:dtNTJuQm/IfNd2NxZzr8RRkBnUK3gDh+RN3G48Wn0mo=,tag:Zf6cEIuYsil2SD06cya9MQ==,type:str]
    server: ENC[AES256_GCM,data:hSGvcy5ZkJGd+9CsQ70F/mIgZKg=,iv:NPq+6sn5EL1GjvuShuM6MDONs+VhMVhUIXfyReN9f1Q=,tag:9LGqXh06KTakb7NFVM/ITw==,type:str]
    theater_remote: ENC[AES256_GCM,data:Iib6vudh/DHkWNgIvC6dNvHWZHc=,iv:ReFxuG6Brlr7qOvSElUprKI5Pms+xMiWaHwuCEKWqCE=,tag:3wc34+Y0faEwnRSc4esbJw==,type:str]
    zigbee2mqtt: ENC[AES256_GCM,data:7EHKzdMbzWHNJW9xgWeSg3RZjtY=,iv:niXPpHnhd1O4kP3vxefJW/YLHrCLQ4kAD5kyRBAwZ98=,tag:D+0yA7MC+7ZA+1VRWECvqQ==,type:str]
nanoGpt:
    apiKey: ENC[AES256_GCM,data:titqOxia/8dtFZJ6zf3cSFNZB2M4sqC2qm+HdfRKJTpMEzSPwh0Lyk/DNlk=,iv:6Iv8oK+QZSY6wO1Kn0gTzwIYKqs3MPu6gYU3BpN8SLY=,tag:zI5XZFqY56B+L3Wfs/0rGA==,type:str]
onlyoffice: ENC[AES256_GCM,data:nM2Q7Kc3XgOORXCVu5FGSdv5pSyWTo89njmVwRkdLVg=,iv:PDn11YPBI0ceKwe/tIw9Ll6YHauNIDHpcBTvUlhbMYw=,tag:haueKAv7n/4Dry6a/BChOA==,type:str]
openWebui: ENC[AES256_GCM,data:vydyre4CoCwC6uPOwEVfhdOHhsWzn9UggjJ3PSlokvVJOF6jYmA=,iv:kuKzZt1A++Z5aPLUWmYiWJ/tIwY/HOAbDcB5J7OV5ew=,tag:V6Bm6xZcaEZOEAsaNAA4MQ==,type:str]
owncloud:
    admin: ENC[AES256_GCM,data:FjFo8poJe+Ggup/iXFEQWrK9V3Q=,iv:UL6+gRD0tQGFdgbIyySsIWPp1QCyd6QH/njCbpyPvhI=,tag:S+nvEvHjH+Xp149Qh3iYjA==,type:str]
    db: ENC[AES256_GCM,data:9xt9JsfOMCemd+dLiDVwk0k6KMs=,iv:NGcchNbDBFKF+DTVwAsJdz2Ox/QjQCamIgEAXlXSB34=,tag:V0lJ8LirPalwYY7P9AWQxg==,type:str]
pihole: ENC[AES256_GCM,data:GeGAnRHjB6fbNt2uzm2tNeWw9sQ=,iv:8fuOrYAOGt+uxDcz3y/7Q3at1pS4nWiyiJeTF3hEuXM=,tag:UFC2Yq8KWVGBf7N6yciAnQ==,type:str]
samba: ENC[AES256_GCM,data:D3RnhtEi7X7UK2SG0p7OBdEoLN7LqL7H44MlzKVeya68/aybrvbctEDsEfmC1R4=,iv:tYma0Max8won/qRy7arA67WZ0QeBfgmQGDw27z8M7hM=,tag:+6qgvKD6ReOgjs5ZuabqIQ==,type:str]
searxng: ENC[AES256_GCM,data:emJyQ/tbwrYPO6tSgVy2lDxKvS8=,iv:ZvsY856kuoIhzPRifeqo08Ozrpb5BIUiy+u2PWuG+Xw=,tag:dV9zr1pdWZB6OIhFKNla+A==,type:str]
smtp2go: ENC[AES256_GCM,data:yTn6SaddjD66/RSrfTAESw==,iv:Givpq1AJ0eSAJ7tJTlzEjdsivn5j5bsai5rJMInQ2Zg=,tag:mljcJ9velAZW9P2uJ1/03Q==,type:str]
ups: ENC[AES256_GCM,data:VB4nAHiMTO0t9gW+3kEphGnOLwo=,iv:PLv8fEPMJ6ffBQaSLkp7vcPquv0H+Eskr7YA5G9TsCg=,tag:D3MpeAwyz+fda+EOd2BwuQ==,type:str]
zwave: ENC[AES256_GCM,data:3bkIzaoF52gJ2+8g7YHMELJfQT4=,iv:ba6UJ0wJbLeQctfkoUvqk/zi5rNexTCGohyxam3+Ip8=,tag:IJXO7u8HVcztKa6UwdFD8w==,type:str]
zwave_hashed: ENC[AES256_GCM,data:RTIX6xP/URFRs70x/68VhhRpMQr1gbamxsgY82spHNsbJTbcTguKIQ5NTTsTrTf58maYRD4AgcxGpxPJ,iv:lYz9UY0GY35T8bYnsEPHAUyrWgrh23RMAlwKK2iqdKs=,tag:b2+qNc66aFRvsOlmDA2+2A==,type:str]
sops:
    age:
        - recipient: age1jxuf7pg7vpcye928qgx3uxzvgcrrpac5pn4844yphctpvuef530qqs59wh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibFRwVzFDY0hkaE9JbmZ6
            Si9vWHY5SVB6aVI4VVgxU0REUW0venZrSkI4ClUyMVN1dHkyMmhlclZnQ3FpQ2Jy
            M3prV1puVGN3dmZINzFTa0hiRVZuQ3cKLS0tIEo5Yi8wZlBxTlA0Zml2aW1lczVi
            TXNJY2NUZ21HQkVqN01CODlCdTR1RzAKV1aimjm66eojEtwZAAWYORgM73b7DOmX
            azqvSCP+brEjBYQXzCvIM6SrEVjp0b+1oa4/SjG0gwCogeXaBoDiDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd3pdegptd0jz3pktjjv3c4z9e6l6jpywlrgp8kftnrp8arjvp0qujyk2q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dTVvbU9RNlp1WWVGUXl1
            bENLTWJ0Nm1zRXMxeFN6RmI2aFBkbUJUWlVvCkZONHNNcFdnUE5MTzJFa2NEaU1R
            akJ5c1JuTHgwWEVWQ21Pakx6ZHpEb3cKLS0tIDk4K29lQXhZN2lVZWxJeE82Uk1Y
            dVJmL2piYlIwelIyeUxBTGZnSGdqMk0K1bdS/0s8TYdL6vGz2Z1lf3YJ7E+bnSK0
            69lNHPz/xX5UhjzH7lFZB3TMeIpWf9rlkYBge1QPsA/nctByejY0CQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t2mg5qfgnh9jt0h824yprvux7hl837sxhqn8lgacxa4msm53hspqpx8q9t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUitvZ3JoTG9nRVFvM3ln
            dHRMdllmNkNnbFJRbzhlaWh4VDBLRmg5N0VjCjRPbXRzNmhGV01ySE1ZcHgzVVgv
            V1QwOTN4SFBIeUgyU2ZZZkRxT0oyTjQKLS0tIC9YZytDRTIwU1htcTdHSGdkOFd1
            S1BSN2RoOWNyTWhRK1c4UUd4TXlWUDAKd4EFIfXebztUjOh6HCsTYYatgX7ok5ay
            Mg1TfWXwLm0PxaPIXDABNT4QAtAKxCgk3bN8D2gjIoK4ngP0GO6LJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1txypm409yzc6hwyepjgnj288ph4c43mdme9c354a45msc69hjpts0p3903
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHBrOUlHcVJXc1U4OWcy
            N2pzdDRscFFiMHEra3JGUXlRMTJtdkw4a3dFCnl4OGxrZS9YSnE4MFE3TzRiU3BT
            ZjJxbHd6WW50NDZncFVFYWloUEViaU0KLS0tIHpxRFYvVkQ0Yi9CTWZaWDgwM0FI
            alRzTVY5SnEyc2cycytaN0t4d3kxajgKvKiWV42SC4vh1hwzPaAFN8BovI9cI3Dy
            lvRKJ8lcLGStHhAABtEwgituPcgJFoqQaWl3za8nWzuvIvhNdDEGdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14mtzynemax29ls25wk7s72lfnsmqwsxd3suj7a24zxprkkxufqtqfmkq4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSUN6djhRWnh4dDVqdS9x
            QjBlOEVUZk9Qb3V3SWhzeEhwS0VFZ1dDYW1NCjRyWERKQ2hQVzBLZGF3UTRaT2VP
            NkFreUs3Tk9za1NQdHI5OUdoOEFRYjAKLS0tIGhpeWtVN3JqSkliSC9JT1dtZ3FC
            M2d4M1lXVEhZQXlNYzhGVGR5dW0wU1UK+00X0k4AhwF9Z8XF9cvqNwgNTgAC+zMA
            fyx7zbgoVNUo95s+CrkLS94AQ6eVIdYvff/bJw0WUH1EZlFv1Fr0qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u8f5qmensfddyqcrhzy59uyc5qas400lkvmystkvasxgm3clw9kqs2aya0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWhqa1VXd1Rnb2VqU0Yv
            MGtjc3FXMXRKL2FER3pZS1FWcUdxR3NRN1g4Ck5VUEZzemNvTWRjVnY2YkkyVGN0
            djZCb3ZBVHUzc1VGcnVoQmNhbEEySEUKLS0tIFpkdkNNTHZZK3lmREYza2FYZTZ1
            Zkg0bXdCcHg4OCtSN2pQa2txR0lPcm8KQXUtPNCAnc2o+oaP7Opvlpf75UaVStNa
            mcZH0CH61mCdrYui6qyr6EOpf7yQTMlEDkyejuNBmr0bdsSou6ZWbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T22:48:03Z"
    mac: ENC[AES256_GCM,data:cFz/za3pAhQs5dVCfPvawxN7Ywh0uvfQlnTqCc/6ajnv2S92Ex6r80imojOBqXQeUMAub5oWdjPA4D6zDfXrOl65ZJ6/fMNE4ThBG3AZafJnmrPp5mRFh9tNNISyzAkroFRftu3SQzOzD1oypWCcg9jY/0Uvp6Hls3JRtfU1uko=,iv:ue08snZR9Vh0XGypWx1JG1LC5+Ptlbo1XmnZ24iknkc=,tag:Lr1+6sg+rNKicZ5T4vnNiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
